// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Gecko {

	using System;

	public delegate void NewWindowHandler(object o, NewWindowArgs args);

	public class NewWindowArgs : GLib.SignalArgs {
		public Gecko.WebControl NewEmbed{
			set {
				Args[0] = (Gecko.WebControl) value;
			}
		}

		public uint Chromemask{
			get {
				return (uint) Args[1];
			}
		}

	}
}
