// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Gtk {

	using System;

	public delegate void NewWindowHandler(object o, NewWindowArgs args);

	public class NewWindowArgs : GtkSharp.SignalArgs {
		public Gtk.GeckoWebControl NewEmbed{
			set {
				Args[0] = (Gtk.GeckoWebControl) value;
			}
		}

		public uint Chromemask{
			get {
				return (uint) Args[1];
			}
		}

	}
}
